#spring.application.name=express
#server.port=8090
#spring.datasource.url=jdbc:mysql://localhost:3306/bishe
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=123456
#???properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bishe?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  jackson:
    time-zone: Asia/Shanghai

server:
  port: 8090

logging:
  level:
    org:
      apache:
        ibatis=DEBUG:

mybatis:
  mapper-locations: classpath*:generator/mapper/*.xml
  type-aliases-package: org.example.generator.entity
# application.yml
# accessKeyId:注册阿里云密钥,用于上传头像
oss:
  endpoint: oss-cn-hangzhou.aliyuncs.com
  accessKeyId:
  accessKeySecret: txpLq6GCvwqsRdjuOvMvTD7VJsyQOs
  bucketName: my-app-avatar

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
#mybatis-plus:
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete: false
#  mapper-locations: classpath*:generator/mapper/*.xml
#  type-aliases-package: org.example.generator.entity


